common_packages:
  - aide
  - nftables
  - rsyslog
  - auditd
  - audispd-plugins
  - libpam-pwquality
  - acl
  - libpam-runtime

removed_packages:
  - xorg-x11-server-common
  - ntp
  - net-snmp
  - samba
  - squid
  - telnet
  - talk
  - rsh
  - xinetd
  - chrony
  - openldap-servers
  - dovecot
  - httpd
  - apache2
  - vsftpd
  - bind
  - nis
  - gdm
  - inetutils-telnet
  - ftp
  - tnftp
  - ufw

