auth_authpriv: "/var/log/auth.log"
rsyslog_main: "/var/log/mail.log"
rsyslog_kernel: "/var/log/kern.log"
all_warn_error: "/var/log/warn"
all_critical: "/var/log/crit"
mail_info: "/var/log/mail.info"
mail_warning: "/var/log/mail.warn"
mail_error: "/var/log/mail.err"
news_crit: "/var/log/news/news.crit"
news_err: "/var/log/news/news.err"
news_notice: "/var/log/news/news.notice"
mail_news_none: "/var/log/messages"
all_emergency: ":omusermsg:*"
local0_local1: "/var/log/local/messages"
local2_local3: "/var/log/local/messages"
local4_local5: "/var/log/local/messages"
local6_local7: "/var/log/local/messages"
