kex_algorithms: "ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256"
macs: " hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512,hmac-sha2-256"
ciphers: "aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes128-ctr"
log_level: "INFO"
login_grace_time: "60"
permit_root_login: "no"
max_auth_tries: "4"
max_sessions: "6"
hostbased_authentication: "no"
rhosts: "yes"
empty_passwords: "no"
kbd: "no"
pam: "yes"
tcp_forwarding: "no"
x11_forwarding: "no"
print_motd: "no"
idle_timeout: "300"
max_count: "3"
max_startups: "10:30:60"
allow_users: "sysadmin"
banner: "/etc/issue.net"
accept_env: "LANG LC_*"
subsystem_sftp: "/usr/lib/openssh/sftp-server"
ssh_port: 22
gracetime: 60
max_auth: 4
max_session: 6
ClientAliveInterval: 300
ClientAliveCountMax: 3
allowed_group: [sugroup]
root_login: "no"